const missions = [
  {
    act: "Acto I",
    title: "Pista en ruinas",
    location: "Aeropuerto de Teheran, borde occidental",
    goal: "Cruzar la pista, llegar a un bombero y sostener la primera entrevista.",
    brief:
      "Una pista civil convertida en corredor militar. La primera version oficial se cae con un solo testigo vivo.",
    portrait: "assets/personaje/castro_1.jpg",
    portraitTitle: "Nelson entra con camara y casco",
    portraitBody: "La referencia visual define la silueta: casco azul, microfono y chaleco PRESS.",
    background: {
      image: "assets/backgrounds/mission_01.png",
      credit: "Base fotografica de Nihar Reddy Jangam, convertida a pixel-art local.",
      link: "https://unsplash.com/photos/airplanes-parked-on-a-wet-tarmac-at-night-soEvHwmj5zQ",
    },
    source: {
      name: "Farhad Nouri",
      role: "Bombero aeroportuario",
      quote: "Primero evacuaron a la prensa. Despues trajeron cajas sin sellos.",
    },
    evidence:
      "Farhad confirma que los hangares civiles fueron usados para mover cargamentos militares antes del ataque.",
    extractLabel: "Van satelital",
    startLog: [
      "Productora: Nelson, aire hostil. Queremos voces, no solo humo.",
      "Nelson: Dame treinta segundos de silencio y te consigo portada.",
    ],
    winLog: [
      "Farhad: Si esto sale al aire, ya no podran fingir sorpresa.",
      "Nelson: Guardalo. La cinta ahora vale mas que el combustible.",
    ],
    palette: {
      sky: "#6a5749",
      haze: "#9c7d65",
      far: "#47392f",
      mid: "#5d493d",
      ground: "#241c18",
      surface: "#725845",
      signal: "#e3bf63",
    },
    levelWidth: 2320,
    groundY: 152,
    sourceX: 970,
    exitX: 2190,
    skyline: [28, 44, 36, 56, 41, 33],
    platforms: [
      { x: 210, y: 132, w: 32, h: 10, tint: "#886a54" },
      { x: 420, y: 122, w: 54, h: 10, tint: "#7a5f4b" },
      { x: 745, y: 136, w: 44, h: 8, tint: "#896d58" },
      { x: 1100, y: 128, w: 50, h: 10, tint: "#7a614d" },
      { x: 1470, y: 120, w: 68, h: 10, tint: "#765943" },
      { x: 1770, y: 134, w: 36, h: 10, tint: "#886c57" },
    ],
    initialEnemies: [
      { type: "rifle", x: 340 },
      { type: "rifle", x: 520 },
      { type: "drone", x: 770, y: 84 },
      { type: "rifle", x: 1270 },
      { type: "heavy", x: 1560 },
      { type: "rifle", x: 1860 },
    ],
    interviewWaves: [
      { delay: 0.9, spawns: [{ type: "rifle", edge: "right" }, { type: "rifle", edge: "right" }] },
      { delay: 3.0, spawns: [{ type: "drone", edge: "left" }, { type: "rifle", edge: "right" }] },
      { delay: 5.5, spawns: [{ type: "heavy", edge: "right" }] },
    ],
    extractionWave: [{ type: "rifle", edge: "right" }, { type: "drone", edge: "left" }],
  },
  {
    act: "Acto I",
    title: "Hospital de campana",
    location: "Barrio sur, hospital improvisado",
    goal: "Proteger a una medica que trabaja entre cortes de energia y morteros.",
    brief:
      "El hospital funciona con generadores viejos y camillas prestadas. Cada explosivo tapa una historia distinta.",
    portrait: "assets/personaje/castro_2.jpg",
    portraitTitle: "Casco TN en la cabina",
    portraitBody: "La segunda referencia aporta expresion contenida y perfil frontal para el retrato operativo.",
    background: {
      image: "assets/backgrounds/mission_02.png",
      credit: "Base fotografica de Adhitya Sibikumar, convertida a pixel-art local.",
      link: "https://unsplash.com/photos/dark-hospital-hallway-with-warm-light-xTi__UtunmA",
    },
    source: {
      name: "Dra. Darya Farhadi",
      role: "Medica de guardia",
      quote: "No nos faltan camas. Nos faltan minutos antes del proximo impacto.",
    },
    evidence:
      "Darya documenta que los civiles fueron desviados de corredores seguros minutos antes del bombardeo.",
    extractLabel: "Ambulancia blindada",
    startLog: [
      "Productora: Necesito pruebas de que el hospital seguia abierto.",
      "Nelson: Si sigue en pie, sale al aire. Si no, sale igual.",
    ],
    winLog: [
      "Darya: Mostra esto completo. Ningun recorte lo vuelve menos cierto.",
      "Nelson: El problema no es filmar. El problema es que no lo tapen.",
    ],
    palette: {
      sky: "#4d4d43",
      haze: "#85765b",
      far: "#3d352c",
      mid: "#56473a",
      ground: "#1c1714",
      surface: "#6d5a48",
      signal: "#d9b863",
    },
    levelWidth: 2440,
    groundY: 150,
    sourceX: 1080,
    exitX: 2295,
    skyline: [24, 31, 49, 40, 58, 46, 34],
    platforms: [
      { x: 260, y: 132, w: 44, h: 10, tint: "#7f6551" },
      { x: 590, y: 118, w: 58, h: 10, tint: "#6e5948" },
      { x: 925, y: 130, w: 38, h: 8, tint: "#8d715c" },
      { x: 1310, y: 122, w: 56, h: 10, tint: "#775f4c" },
      { x: 1700, y: 126, w: 50, h: 10, tint: "#6d5747" },
      { x: 1985, y: 138, w: 40, h: 8, tint: "#866a57" },
    ],
    initialEnemies: [
      { type: "rifle", x: 330 },
      { type: "drone", x: 650, y: 78 },
      { type: "rifle", x: 860 },
      { type: "heavy", x: 1410 },
      { type: "rifle", x: 1740 },
      { type: "drone", x: 2070, y: 74 },
    ],
    interviewWaves: [
      { delay: 1.2, spawns: [{ type: "rifle", edge: "left" }, { type: "rifle", edge: "right" }] },
      { delay: 3.4, spawns: [{ type: "drone", edge: "right" }] },
      { delay: 5.8, spawns: [{ type: "heavy", edge: "left" }, { type: "rifle", edge: "right" }] },
    ],
    extractionWave: [{ type: "heavy", edge: "right" }, { type: "rifle", edge: "left" }],
  },
  {
    act: "Acto II",
    title: "Caravana nocturna",
    location: "Ruta de evacuacion al norte",
    goal: "Entrevistar a un chofer de desplazados y salir con la grabacion antes del amanecer.",
    brief:
      "Los civiles se mueven sin luces y con los vidrios cubiertos. El chofer sabe quien desvio a la caravana.",
    portrait: "assets/personaje/castro_3.jpg",
    portraitTitle: "Transmision en campo abierto",
    portraitBody: "La tercera imagen fija el gesto del corresponsal en exterior: mano alta, microfono y terreno expuesto.",
    background: {
      image: "assets/backgrounds/mission_03.png",
      credit: "Base fotografica de Ed Wingate, convertida a pixel-art local.",
      link: "https://unsplash.com/photos/a-car-is-driving-down-a-mountain-road-fNJ4F9d4KF4",
    },
    source: {
      name: "Reza Moin",
      role: "Chofer de evacuacion",
      quote: "Nos mandaron por la ruta vieja. Ahi ya sabian que iba a caer fuego.",
    },
    evidence:
      "Reza identifica un desvio deliberado de convoyes civiles hacia una carretera marcada como segura.",
    extractLabel: "Pickup de enlace",
    startLog: [
      "Productora: La senal viene y va. No pierdas al chofer.",
      "Nelson: Si se mueve la verdad, yo corro atras.",
    ],
    winLog: [
      "Reza: Anota las patentes. Siempre vuelven los mismos camiones.",
      "Nelson: Si vuelven, los vamos a esperar con la camara prendida.",
    ],
    palette: {
      sky: "#2d302f",
      haze: "#635e4f",
      far: "#252421",
      mid: "#403a33",
      ground: "#161412",
      surface: "#5a4c41",
      signal: "#d7bb66",
    },
    levelWidth: 2520,
    groundY: 154,
    sourceX: 1180,
    exitX: 2390,
    skyline: [12, 20, 15, 28, 24, 17],
    platforms: [
      { x: 220, y: 136, w: 46, h: 8, tint: "#68574a" },
      { x: 515, y: 126, w: 58, h: 8, tint: "#6e5a49" },
      { x: 890, y: 118, w: 52, h: 10, tint: "#776353" },
      { x: 1370, y: 130, w: 66, h: 8, tint: "#6b594c" },
      { x: 1715, y: 122, w: 52, h: 10, tint: "#7c6654" },
      { x: 2100, y: 136, w: 42, h: 8, tint: "#6a5a4f" },
    ],
    initialEnemies: [
      { type: "rifle", x: 320 },
      { type: "heavy", x: 690 },
      { type: "drone", x: 960, y: 82 },
      { type: "rifle", x: 1440 },
      { type: "rifle", x: 1760 },
      { type: "drone", x: 2050, y: 70 },
    ],
    interviewWaves: [
      { delay: 1.0, spawns: [{ type: "rifle", edge: "right" }, { type: "drone", edge: "left" }] },
      { delay: 3.0, spawns: [{ type: "heavy", edge: "right" }] },
      { delay: 5.4, spawns: [{ type: "rifle", edge: "left" }, { type: "rifle", edge: "right" }] },
    ],
    extractionWave: [{ type: "drone", edge: "right" }, { type: "heavy", edge: "left" }],
  },
  {
    act: "Acto III",
    title: "Archivo estatal",
    location: "Edificio de television publica",
    goal: "Asegurar una entrevista con una archivista y salir con los brutos sin editar.",
    brief:
      "Las cintas buenas estan en un sotano sellado. Una editora conoce la secuencia exacta de recortes y censura.",
    portrait: "assets/personaje/castro_1.jpg",
    portraitTitle: "Retrato de terreno bajo humo",
    portraitBody: "La referencia vuelve como ficha de prensa: Nelson cubre una operacion de borrado.",
    background: {
      image: "assets/backgrounds/mission_04.png",
      credit: "Base fotografica de Gabriel Weyand, convertida a pixel-art local.",
      link: "https://unsplash.com/photos/a-video-production-studio-with-a-monitor-displaying-multiple-screens-X8uonmU2Ssw",
    },
    source: {
      name: "Leila Nasseri",
      role: "Archivista de television",
      quote: "No mintieron con una frase. Mintieron con cada segundo que sacaron.",
    },
    evidence:
      "Leila entrega el orden real de edicion y prueba que la cadena estatal borro impactos y convoyes.",
    extractLabel: "Ascensor de servicio",
    startLog: [
      "Productora: Si salis con esas cintas, cambia toda la pieza.",
      "Nelson: Entonces no salgo sin ellas.",
    ],
    winLog: [
      "Leila: Si cortan la antena, subilo igual. Que alguien vea la secuencia completa.",
      "Nelson: Esta vez no van a editar el final.",
    ],
    palette: {
      sky: "#4a443f",
      haze: "#726757",
      far: "#312d29",
      mid: "#51483f",
      ground: "#191614",
      surface: "#625345",
      signal: "#ddc36a",
    },
    levelWidth: 2460,
    groundY: 148,
    sourceX: 1120,
    exitX: 2320,
    skyline: [38, 52, 64, 48, 55, 41],
    platforms: [
      { x: 250, y: 126, w: 56, h: 10, tint: "#75624f" },
      { x: 640, y: 112, w: 44, h: 10, tint: "#7d6755" },
      { x: 950, y: 120, w: 62, h: 10, tint: "#6b594b" },
      { x: 1320, y: 106, w: 58, h: 10, tint: "#806b59" },
      { x: 1710, y: 118, w: 66, h: 10, tint: "#725f4e" },
      { x: 2085, y: 130, w: 52, h: 8, tint: "#857160" },
    ],
    initialEnemies: [
      { type: "rifle", x: 330 },
      { type: "drone", x: 590, y: 68 },
      { type: "heavy", x: 880 },
      { type: "rifle", x: 1480 },
      { type: "drone", x: 1870, y: 76 },
      { type: "heavy", x: 2140 },
    ],
    interviewWaves: [
      { delay: 1.1, spawns: [{ type: "rifle", edge: "left" }, { type: "rifle", edge: "right" }] },
      { delay: 3.6, spawns: [{ type: "heavy", edge: "right" }, { type: "drone", edge: "right" }] },
      { delay: 6.0, spawns: [{ type: "rifle", edge: "left" }] },
    ],
    extractionWave: [{ type: "heavy", edge: "right" }, { type: "drone", edge: "left" }],
  },
  {
    act: "Acto IV",
    title: "Azotea de transmision",
    location: "Distrito central, torre de enlace",
    goal: "Entrevistar al exasesor, sostener la senal y emitir la pieza final bajo asedio.",
    brief:
      "Todos los testimonios apuntan a la misma operacion. El ultimo hombre conoce la orden que conecto propaganda y fuego real.",
    portrait: "assets/personaje/castro_2.jpg",
    portraitTitle: "Mirada fija antes del vivo",
    portraitBody: "La referencia frontal funciona como retrato de cierre: senal al limite, presion total, voz firme.",
    background: {
      image: "assets/backgrounds/mission_05.png",
      credit: "Base fotografica de Nourieh Ferdosian, convertida a pixel-art local.",
      link: "https://unsplash.com/photos/hazy-cityscape-with-tall-buildings-and-a-distant-tower-vN2TM-qNOo0",
    },
    source: {
      name: "Behrouz Qasemi",
      role: "Exasesor de comunicacion militar",
      quote: "La consigna era simple: si no podian ocultar el ataque, habia que editar a los testigos.",
    },
    evidence:
      "Behrouz vincula ordenes de propaganda, bloqueo de corredores y destruccion de imagenes en una misma cadena de mando.",
    extractLabel: "Uplink en vivo",
    startLog: [
      "Productora: Ultima ventana de satelite. Despues de esto, quedas solo.",
      "Nelson: Con una antena, una fuente y medio minuto me alcanza.",
    ],
    winLog: [
      "Behrouz: Ahora ya no depende de ellos. Depende de quien quiera mirar.",
      "Nelson: Perfecto. Que miren.",
    ],
    palette: {
      sky: "#413b37",
      haze: "#6c6258",
      far: "#2c2724",
      mid: "#4a423a",
      ground: "#171412",
      surface: "#5c5149",
      signal: "#f0cb67",
    },
    levelWidth: 2600,
    groundY: 146,
    sourceX: 1320,
    exitX: 2450,
    skyline: [52, 68, 74, 59, 66, 71],
    platforms: [
      { x: 300, y: 124, w: 44, h: 10, tint: "#796655" },
      { x: 690, y: 108, w: 62, h: 10, tint: "#6d5d50" },
      { x: 1080, y: 116, w: 50, h: 10, tint: "#8a735e" },
      { x: 1490, y: 98, w: 76, h: 10, tint: "#725f50" },
      { x: 1850, y: 114, w: 54, h: 10, tint: "#806c5b" },
      { x: 2210, y: 126, w: 44, h: 8, tint: "#6a5b4f" },
    ],
    initialEnemies: [
      { type: "heavy", x: 380 },
      { type: "rifle", x: 740 },
      { type: "drone", x: 980, y: 72 },
      { type: "heavy", x: 1620 },
      { type: "drone", x: 1960, y: 66 },
      { type: "rifle", x: 2230 },
    ],
    interviewWaves: [
      { delay: 1.2, spawns: [{ type: "heavy", edge: "left" }, { type: "rifle", edge: "right" }] },
      { delay: 3.0, spawns: [{ type: "drone", edge: "left" }, { type: "drone", edge: "right" }] },
      { delay: 5.0, spawns: [{ type: "heavy", edge: "right" }, { type: "rifle", edge: "left" }] },
      { delay: 7.2, spawns: [{ type: "heavy", edge: "right" }] },
    ],
    extractionWave: [{ type: "drone", edge: "right" }, { type: "heavy", edge: "left" }, { type: "rifle", edge: "right" }],
  },
];
